services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scraper_db
    ports:
      - published: 5432
        target: 5432

  adminer:
    image: adminer
    ports:
      - published: 8080
        target: 8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: postgres
volumes:
  data: